builds:
  - binary: say 
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true 

brews:
  -
    name: say
    homepage: samlhuillier.github.io
    tap:
      owner: samlhuillier
      name: homebrew-say
    commit_author:
      name: samlhuillier
      email: sam.jansa123@gmail.com
